### ISSUE TITLE
Add "Research" page

### ISSUE THREAD

**Issue by tdido** [cnio-bu/website#4]

**Comment by tdido** [comment]
The "Blog" page type may be a good candidate for this one.

**Comment by ggomezl** [comment]
Cancer multi-omics and precision medicine
---------------

Identifying the most appropriate therapies from cancer genome data is a major challenge in personalized cancer medicine. Physicians and researchers are faced with long lists of tumor-specific multi-omics alterations (e.g. mutations, gene deletions and amplifications, overexpressed genes, etc.) which are either clinically “unactionable”, their biological role unknown or they are irrelevant for tumor biology. 

Our group is interested in the development of novel bioinformatics methods to interpret multi-omics alterations, evaluate their clinical relevance and drug feasibility and provide a prioritized evidence-based list of tailored anticancer therapies to facilitate clinical decision making. To this aim we have developed [PanDrugs](https://pandrugs.org/), a bioinformatics platform to prioritize anticancer drug treatments according to individual multi-omics data.


Drug repositioning
---------------

Computational drug repositioning consists in finding new applications to already approved drugs by using computational methods. Our lab is interested in  drug-associated gene expression signatures coming from large pharmacogenomics projects, drug structural info and AI and machine learning algorithms to infer new potential therapeutical applications, to predict cancer drug response and to infer synergistic combinations of antitumor drugs.

For this purpose, we have developed [Beyondcell](https://github.com/cnio-bu/beyondcell), a computational methodology for identifying tumour cell subpopulations with distinct drug responses in single-cell RNA-seq data and proposing cancer-specific treatments.


Tumour microenvironment and immunotherapy
---------------

Our lab is interested in to optimize the immune response to fight cancer while avoiding runaway immune responses that would damage normal tissues. To do so, we have developed [DREIMT](https://dreimt.org/), a tool and a database for hypothesis generation and drug prioritization capable of modulating immune cell activity from transcriptomics data.


Cancer vulnerability
---------------

Cancer precision medicine has achieved promising results in the clinical practice, although only a small fraction of patients present the particular biomarkers of drug sensitivity to take benefit of this approach. Our group is interested in identifying novel druggable cancer dependencies in order to expand the current catalogue of targeted therapies for cancer treatment. To achieve this, we have developed [VulcanSpot](http://www.vulcanspot.org/) which integrates molecular profiling with gene essentiality screenings in cancer cell lines in order to identify gene dependencies.


GENCODE
---------------

[GENCODE](https://www.gencodegenes.org/) is a scientific project in genome research and part of the ENCODE (ENCyclopedia Of DNA Elements) scale-up project. The GENCODE consortium was initially formed as part of the pilot phase of the ENCODE project to identify and map all protein-coding genes within the ENCODE regions (approx. 1% of Human genome). GENCODE now aims to build an “Encyclopedia of genes and genes variants” by identifying all gene features in the human and mouse genome using a combination of computational analysis, manual annotation, and experimental validation, and annotating all evidence-based gene features in the entire human genome at a high accuracy. 

[CNIO](https://www.cnio.es/) is one of the members of the GENCODE consortium and carries out the computational analysis of coding genes and gene models. The [APPRIS](https://appris.bioinfo.cnio.es/#/) database and web server, developed by our group, selects a single representative protein isoform for each coding gene based on cross-species conservation and the preservation of protein structural and functional features.
